'use client';

import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { FaRobot, FaFileAlt, FaLock, FaFileDownload } from 'react-icons/fa';

export default function AboutPage() {
  return (
    <>
      <Header />
      <div className="container mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold mb-8 text-center">About SmartDocGen</h1>
        
        <section className="bg-white rounded-lg shadow-md p-8 mb-12">
          <h2 className="text-2xl font-bold mb-4">Our Mission</h2>
          <p className="text-gray-700 mb-6">
            SmartDocGen was created to simplify the process of generating legal documents by leveraging
            the power of artificial intelligence. Our mission is to make legal document creation
            accessible, efficient, and accurate for everyone.
          </p>
          <p className="text-gray-700">
            Whether you're a small business owner, freelancer, or individual needing legal
            documentation, SmartDocGen provides an intuitive platform to create professional documents
            in minutes, without the complexity and cost typically associated with legal document
            preparation.
          </p>
        </section>
        
        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-6 text-center">Key Features</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            <div className="card flex flex-col items-center text-center">
              <div className="bg-primary/10 p-4 rounded-full mb-4">
                <FaRobot className="w-8 h-8 text-primary" />
              </div>
              <h3 className="text-xl font-semibold mb-2">AI-Powered Generation</h3>
              <p className="text-gray-600">
                Leverages advanced AI models to generate legally sound document content based on your inputs.
              </p>
            </div>
            
            <div className="card flex flex-col items-center text-center">
              <div className="bg-primary/10 p-4 rounded-full mb-4">
                <FaFileAlt className="w-8 h-8 text-primary" />
              </div>
              <h3 className="text-xl font-semibold mb-2">Multiple Document Types</h3>
              <p className="text-gray-600">
                Create various legal documents including contracts, agreements, and notices for different purposes.
              </p>
            </div>
            
            <div className="card flex flex-col items-center text-center">
              <div className="bg-primary/10 p-4 rounded-full mb-4">
                <FaLock className="w-8 h-8 text-primary" />
              </div>
              <h3 className="text-xl font-semibold mb-2">Secure Processing</h3>
              <p className="text-gray-600">
                Your document data is processed securely and never stored permanently without your permission.
              </p>
            </div>
            
            <div className="card flex flex-col items-center text-center">
              <div className="bg-primary/10 p-4 rounded-full mb-4">
                <FaFileDownload className="w-8 h-8 text-primary" />
              </div>
              <h3 className="text-xl font-semibold mb-2">Export Options</h3>
              <p className="text-gray-600">
                Download your generated documents in PDF format for easy sharing, printing, and archiving.
              </p>
            </div>
          </div>
        </section>
        
        <section className="bg-white rounded-lg shadow-md p-8 mb-12">
          <h2 className="text-2xl font-bold mb-4">How It Works</h2>
          <ol className="list-decimal pl-5 space-y-4">
            <li className="text-gray-700">
              <strong>Select a document type</strong> - Choose from various templates including contracts, agreements, and legal notices.
            </li>
            <li className="text-gray-700">
              <strong>Enter your details</strong> - Provide specific information relevant to your document, such as party names, addresses, and terms.
            </li>
            <li className="text-gray-700">
              <strong>AI generates your document</strong> - Our advanced AI model processes your inputs to create a comprehensive legal document.
            </li>
            <li className="text-gray-700">
              <strong>Review and download</strong> - Review the generated document, make any necessary adjustments, and download it in PDF format.
            </li>
          </ol>
        </section>
        
        <section className="bg-gray-50 rounded-lg p-8">
          <h2 className="text-2xl font-bold mb-4">Legal Disclaimer</h2>
          <p className="text-gray-700 mb-4">
            The documents generated by SmartDocGen are provided for informational purposes only and do not constitute legal advice. While we strive to create accurate and useful documents, the content should be reviewed by a qualified legal professional before use in actual legal situations.
          </p>
          <p className="text-gray-700">
            SmartDocGen is not a law firm and is not a substitute for an attorney or law firm. Use of SmartDocGen does not create an attorney-client relationship.
          </p>
        </section>
      </div>
      <Footer />
    </>
  );
} 